# Generated by Django 5.0.1 on 2024-01-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_juegomod_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comando', models.CharField(default='', max_length=50)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('Moderador', 'Moderador'), ('editor de twitch', 'Editor de Twitch')], max_length=50)),
                ('descripcion', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
