# Generated by Django 5.0.1 on 2024-01-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comando'),
    ]

    operations = [
        migrations.AddField(
            model_name='comando',
            name='canal',
            field=models.CharField(choices=[('chachoyvt', 'ChachoyVT')], default='chachoyvt', max_length=50),
        ),
        migrations.AlterField(
            model_name='comando',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('moderador', 'Moderador'), ('editor de twitch', 'Editor de Twitch')], max_length=50),
        ),
    ]
