# Generated by Django 5.0.1 on 2024-01-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='respuesta',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='asunto',
            field=models.CharField(max_length=1000),
        ),
    ]
