# Generated by Django 5.0.1 on 2024-01-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ticket_respuesta_alter_ticket_asunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(default='', max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ruta/del/directorio/')),
            ],
        ),
    ]
