# Generated by Django 5.0.1 on 2024-01-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='nombre_twitch',
            field=models.CharField(max_length=50),
        ),
    ]
