# Generated by Django 5.0.1 on 2024-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seccion_rename_imagen_equipo_imagen_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
