# Generated by Django 5.0.1 on 2024-01-27 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_seccion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seccion'),
        ),
    ]
