# Generated by Django 5.0.1 on 2024-01-27 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_equipo_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seccion'),
        ),
    ]
